Assignment-war/src/fit5042/Assignment/controllers/manager/ManagerViewController.java
package fit5042.Assignment.controllers.manager;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import javax.el.ELContext;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import fit5042.Assignment.entities.Customer;
import fit5042.Assignment.entities.RelationManager;
import fit5042.Assignment.mbeans.ManagerManagedBean;

@Named("managerViewController")
@RequestScoped
public class ManagerViewController implements Serializable {
	
	@ManagedProperty("ManagerManagedBean")
	ManagerManagedBean managerManagedBean;
	
	private ArrayList<RelationManager> rManagers;
	
	private int searchId;
	
	private boolean showForm = true;
	
	private boolean isShowForm() {
		return showForm;
	}
	
	public ManagerViewController() {
		
		
		rManagers = new ArrayList<>();
		
		ELContext elContext = FacesContext.getCurrentInstance().getELContext();
		
		managerManagedBean = (ManagerManagedBean) FacesContext.getCurrentInstance()
				.getApplication().getELResolver()
				.getValue(elContext, null, "managerManagedBean");
		
		updateManagerList();
	}

	private void updateManagerList() {
		// TODO Auto-generated method stub
			rManagers.clear();
			
			for (fit5042.Assignment.entities.RelationManager rManager : managerManagedBean.getAllManagers())
			{
				rManagers.add(rManager);
			}
			setManagers(rManagers);
	}

	public ArrayList<RelationManager> getManagers() {
		return rManagers;
	}

	public void setManagers(ArrayList<RelationManager> rManagers) {
		this.rManagers = rManagers;
	}
	
	public void searchAll() {
		rManagers.clear();
		for (fit5042.Assignment.entities.RelationManager rManager : managerManagedBean.getAllManagers())
		{
			rManagers.add(rManager);
		}
		setManagers(rManagers);
	}
	
	public void searchManagerById(int managerId) {
		rManagers.clear();
		rManagers.add(managerManagedBean.searchManagerById(managerId));
	}

	public void removeManager(int managerId) {
		
		managerManagedBean.removeManager(managerId);
		searchAll();
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Manager has been succesfully deleted."));
	}

	public int getSearchId() {
		return searchId;
	}

	public void setSearchId(int searchId) {
		this.searchId = searchId;
	}

	
}

Assignment-war/WebContent/RManager/addManager.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title> <!-- #{titleController.pageTitle} --></title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                   <!--  #{titleController.pageTitle}  --> - Add Manager
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
                <h1><h:outputText value="Create"/></h1>
                <table class="table table-bordered ">

                    <tr class="#{!managerName.valid ? 'has-error' : 'none'}">
                        <td width ="200">
                            <h:outputLabel value="Manager Name" for="managerName" />
                        </td>
                        <td>
                            <h:inputText id="managerName" value="#{managerAddController.manager.managerName}" title="managerName" 
                            		required="true" requiredMessage="Please enter manager name.">
							</h:inputText> <br /> <h:message for="managerName"
									class="#{!managerName.valid ? 'label label-warning' : 'none'}" />
                        </td>

                    </tr>
                    
                    
                    <tr class="#{!dept.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Department" for="dept" />
                        </td>
                        <td>
                            <h:inputText id="dept" value="#{managerAddController.manager.dept}" title="dept" 
                            			required="true" requiredMessage="Please enter department!"/> <br />
                            <h:message for="dept" class="#{!dept.valid ? 'label label-warning' : 'none'}" />
                        </td>

                    </tr>
                </table>
				<div>
                <h:commandButton id="submit" value="Submit" action="#{managerAddController.addManager(managerAddController.manager)}" class="btn btn-primary" />
                <h:link id="close" value="Close" outcome="/faces/RManager/viewManager.xhtml"
						          class="btn btn-primary" />
				</div>
				<div>
				<h:link id="home" value="Home" outcome="/faces/Index/index.xhtml"
						          class="btn btn-primary" />
				</div>
				
				
            </h:form>

        </f:view>
            </div>
        </div>

    </h:body>
</html>

Assignment-war/WebContent/RManager/detailManager.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title> <!-- #{titleController.pageTitle}  --> </title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    <!-- #{titleController.pageTitle} - Edit Property  -->
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">
                    <tr>
                        <td width ="150" valign="top"> Manager Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{managerDetailController.manager.managerId}</h:outputLabel>
                        </td>
                    </tr>
                     <tr>
                        <td width ="100" valign="top"> Manager Name:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "managerName" >#{managerDetailController.manager.managerName}</h:outputLabel>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top"> Manager Department: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "dept" >#{managerDetailController.manager.dept}</h:outputLabel>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top"> Customers: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "customer" >
                                #{managerDetailController.getCustomerNames()}
                            </h:outputLabel>

                        </td>
                    </tr>
                   </table>
                 <h:link id="close" value="Close" outcome="/faces/RManager/viewManager.xhtml"
 						          class="btn btn-primary" />

            </h:form>
        </div>
    </h:body>
</html>

Assignment-war/WebContent/RManager/editManager.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title> <!-- #{titleController.pageTitle}  --> </title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    <!-- #{titleController.pageTitle}  --> - Edit Manager
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">

                    <tr>
                        <td width ="150" valign="top"> Manager Id</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{managerEditController.manager.managerId}</h:outputLabel>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top"> Manager Name: </td>
                        <td valign="bottom">
                            <h:inputText id = "managerName" value="#{managerEditController.manager.managerName}" binding="#{managerName}"
                             required="true" requiredMessage="Please enter manager name. ">
							</h:inputText>
                        </td>
                    </tr>
                   
                    <tr>
                        <td width ="100" valign="top"> Manager Department: </td>

                        <td valign="bottom">
                            <h:inputText id = "dept" value="#{managerEditController.manager.dept}"  
                            required="true" requiredMessage="Please enter department. ">
                            </h:inputText>
                        </td>
                    </tr>
                    
                                        
                </table>

                <h:commandButton id="save" value="Save" action="#{managerEditController.editManager(managerEditController.manager)}"  class="btn btn-primary" >
                    <f:param name="managerID" value="#{managerEditController.managerId+1}"/>
                </h:commandButton>
                <h:link id="close" value="Close" outcome="/faces/RManager/viewManager.xhtml"
						          class="btn btn-primary" />

            </h:form>
        </div>
        <div>
        <h:link id="home" value="Home" outcome="/faces/Index/index.xhtml"
						          class="btn btn-primary" /></div>
    </h:body>
</html>

Assignment-war/WebContent/RManager/viewManager.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title> <!-- #{titleController.pageTitle} --> Index</title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                   <!-- #{titleController.pageTitle} --> Manager List
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered table-striped">
                    <!-- For each property in properties ArrayList... -->
                    <tr>
                            <td>
                                <h:outputLabel id="Id" value="Manager Id"  />
                            </td>
                            <td>
                                <h:outputLabel id="name" value="Manager Name"  />
                            </td>

                            <td>
                                <h:outputLabel id="department" value="Department"/>
                            </td>
                           

                     </tr>

                    <ui:repeat id="Myrepeat" value="#{managerViewController.managers}"  var="manager" varStatus="status">

                           <tr>
                            <td>
                                <h:outputText value="#{managerViewController.managers.get(status.index).managerId}" id="managerID" />

                            </td>

                            <td>
                                <h:outputText id="outName" value="#{managerViewController.managers.get(status.index).managerName}"  />
                            </td>
                            <td>
                                <h:outputText id="outDept" value="#{managerViewController.managers.get(status.index).dept}"/>
                            </td>
                            
                            <td>
                              <h:link value="Detail | " outcome="/faces/RManager/detailManager.xhtml">
                              <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                You can get the value from next page using the indexController -->
                                <f:param name="managerID" value="#{managerViewController.managers.get(status.index).managerId}"/>
                              </h:link>

                              <h:link value="Edit | " outcome="/faces/RManager/editManager.xhtml">
                              <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                You can get the value from next page using the indexController -->
                                <f:param name="managerID" value="#{status.index + 1}"/>
                              </h:link>

                                <h:commandLink value="Delete" action="#{managerViewController.removeManager(managerViewController.managers.get(status.index).managerId)}" disabled="#{managerViewController.managers.get(status.index).managerId == null}">
                                </h:commandLink>

                                <h:outputText value=" "/>
                            </td>
                            </tr>
                           
                    </ui:repeat>

                </table>

                <div>
                	
                	<h:commandButton id="add" value="Add" action="/faces/RManager/addManager.xhtml" class="btn btn-primary" />
                	
                    <h:commandButton id="viewAll" value="View All" action="#{managerViewController.searchAll()}" class="btn btn-primary" >
                        <f:param name="managerID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                
                <div>
                    <h:inputText value="#{managerViewController.searchId}" id="searchById" required="true" onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "   />
                    <h:commandButton id="searchId" value="Search by Id" action="#{managerViewController.searchManagerById(managerViewController.searchId)}" class="btn btn-primary" >
                        <f:param name="managerID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                <div>
        			<h:link id="home" value="Home" outcome="/faces/Index/index.xhtml"
						          class="btn btn-primary" />
				</div>
                
            </h:form>
        </div>
    </h:body>
</html>